build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
    - "libsndfile1"
    - "libblas-dev"
    - "liblapack-dev"
    - "libatlas-base-dev"
    - "gfortran"
  python_packages:
    - "torch==2.0.0"
    - "numpy==1.23.5"
    - "numba==0.60.0"
    - "librosa==0.9.1"
    - "scipy==1.14.1"
    - "tensorboard==2.0.0"
    - "soundfile==0.12.1"
    - "matplotlib==3.6.1"
